<?php

return [


    'category' => [
        '0' => 'auth.category0',
        '1' => 'auth.category1',
        '2' => 'auth.category2',
        '3' => 'auth.category3',
        '4' => 'auth.category4',
        '5' => 'auth.category5',
        '6' => 'auth.category6',
        '7' => 'auth.category7',
        '8' => 'auth.category8',
        '9' => 'auth.category9',
        '10' => 'auth.category10',
        '11' => 'auth.category11',
        '12' => 'auth.category12',
        '13' => 'auth.category13',
        '14' => 'auth.category14',
    ],

    // user register

    'taskstatus' => [
        '1' => 'auth.taskstatus1',
        '2' => 'auth.taskstatus2',
        '3' => 'auth.taskstatus3',
        '4' => 'auth.taskstatus4',
        '10' => 'auth.taskstatus10',
        '12' => 'auth.taskstatus12',
        '13' => 'auth.taskstatus13',
    ],

    'taskstatususer' => [
        '1' => 'auth.taskstatususer1',
        '2' => 'auth.taskstatususer2',
        '3' => 'auth.taskstatususer3',
        '4' => 'auth.taskstatususer4',
        '10' => 'auth.taskstatususer10',
        '11' => 'auth.taskstatususer11',
    ],

    'entity' => [
        '0' => 'auth.compentity0',
        '1' => 'auth.compentity1',
        '2' => 'auth.compentity2',
    ],

    'purpose' => [
        '0' => 'auth.purpose0',
        '1' => 'auth.purpose1',
        // '2' => 'auth.purpose2',
        '3' => 'auth.purpose3',
    ],

    'compindustry' => [
        '0' => 'auth.industry0',
		'1' => 'auth.industry1',
		'2' => 'auth.industry2',
		'3' => 'auth.industry3',
		'4' => 'auth.industry4',
		'5' => 'auth.industry5',
		'6' => 'auth.industry6',
		'7' => 'auth.industry7',
		'8' => 'auth.industry8',
		'9' => 'auth.industry9',
		'10' => 'auth.industry10',
		'11' => 'auth.industry11',
    ],

    'position' => [
        '0' => 'auth.position0',
		'1' => 'auth.position1',
		'2' => 'auth.position2',
		'3' => 'auth.position3',
		'4' => 'auth.position4',
		'5' => 'auth.position5',
    ],

    // application register

    'deliveryperiod' => [
        '0' => 'auth.deliveryperiod0',
        '1' => 'auth.deliveryperiod1',
        '2' => 'auth.deliveryperiod2',
        '3' => 'auth.deliveryperiod3',
        '4' => 'auth.deliveryperiod4',
    ],

    'contactmethod' => [
        '0' => 'auth.contactmethod0',
        '1' => 'auth.contactmethod1',
        '2' => 'auth.contactmethod2',
        '3' => 'auth.contactmethod3',
    ],

    'budget' => [
        '0' => 'auth.budget0',
        '1' => 'auth.budget1',
        '2' => 'auth.budget2',
        '3' => 'auth.budget3',
        '4' => 'auth.budget4',
    ],

    'infcgender' => [
        '0' => 'auth.infcgender0',
        '1' => 'auth.infcgender1',
        '2' => 'auth.infcgender2',
        // '3' => '指定なし',
    ],

    'infccountry' => [
        '0' => 'auth.infccountry0',
        '1' => 'auth.infccountry1',
        '2' => 'auth.infccountry2',
        '3' => 'auth.infccountry3',
    ],

    'infcgendertask' => [
        '0' => 'auth.infcgendertask0',
        '1' => 'auth.infcgendertask1',
        '2' => 'auth.infcgendertask2',
        '3' => 'auth.infcgendertask3',
    ],

    'infcmedia' => [
        '0' => 'auth.infcmedia0',
        '1' => 'auth.infcmedia1',
        '2' => 'auth.infcmedia2',
        '3' => 'auth.infcmedia3',
        '4' => 'auth.infcmedia4',
        '5' => 'auth.infcmedia5',
        '6' => 'auth.infcmedia6',
        '7' => 'auth.infcmedia7',
    ],

    'infcgenre' => [
        '0' => 'auth.infcgenre0',
        '1' => 'auth.infcgenre1',
        '2' => 'auth.infcgenre2',
        '3' => 'auth.infcgenre3',
        '4' => 'auth.infcgenre4',
        '5' => 'auth.infcgenre5',
        '6' => 'auth.infcgenre6',
        '7' => 'auth.infcgenre7',
        '8' => 'auth.infcgenre8',
        '9' => 'auth.infcgenre9',
        '10' => 'auth.infcgenre10',
    ],

    'gender' => [
        '0' => 'auth.gender0',
        '1' => 'auth.gender1',
        '2' => 'auth.gender2',
    ],

    'agerange' => [
        '0' => 'auth.agerange0',
        '1' => 'auth.agerange1',
        '2' => 'auth.agerange2',
        '3' => 'auth.agerange3',
        '4' => 'auth.agerange4',
        // '5' => 'auth.agerange5',
        // '6' => 'auth.agerange6',
    ],

    'age' => [
        '0' => 'auth.age0',
        '1' => 'auth.age1',
        '2' => 'auth.age2',
        '3' => 'auth.age3',
        '4' => 'auth.age4',
        '5' => 'auth.age5',
        '6' => 'auth.age6',
    ],


    'city' => [
        '0' => 'auth.city0',
        '1' => '北海道',
        '2' => '青森県',
        '3' => '岩手県',
        '4' => '宮城県',
        '5' => '秋田県',
        '6' => '山形県',
        '7' => '福島県',
        '8' => '茨城県',
        '9' => '栃木県',
        '10' => '群馬県',
        '11' => '埼玉県',
        '12' => '千葉県',
        '13' => '東京都',
        '14' => '神奈川県',
        '15' => '新潟県',
        '16' => '富山県',
        '17' => '石川県',
        '18' => '福井県',
        '19' => '山梨県',
        '20' => '長野県',
        '21' => '岐阜県',
        '22' => '静岡県',
        '23' => '愛知県',
        '24' => '三重県',
        '25' => '滋賀県',
        '26' => '京都府',
        '27' => '大阪府',
        '28' => '兵庫県',
        '29' => '奈良県',
        '30' => '和歌山県',
        '31' => '鳥取県',
        '32' => '島根県',
        '33' => '岡山県',
        '34' => '広島県',
        '35' => '山口県',
        '36' => '徳島県',
        '37' => '香川県',
        '38' => '愛媛県',
        '39' => '高知県',
        '40' => '福岡県',
        '41' => '佐賀県',
        '42' => '長崎県',
        '43' => '熊本県',
        '44' => '大分県',
        '45' => '宮崎県',
        '46' => '鹿児島県',
        '47' => '沖縄県',
        '48' => 'auth.city1',
    ],

    'infcdesirepay' => [
        '0' => 'auth.infcdesirepay0',
        '1' => 'auth.infcdesirepay1',
        '2' => 'auth.infcdesirepay2',
        '3' => 'auth.infcdesirepay3',
        '4' => 'auth.infcdesirepay4',
        '5' => 'auth.infcdesirepay5',
    ],

    'inflstatus' => [
        '' => 'auth.inflstatus',
        '4' => 'auth.inflstatus4',
        '5' => 'auth.inflstatus5',
        '6' => 'auth.inflstatus6',
        '7' => 'auth.inflstatus7',
        '8' => 'auth.inflstatus8',
        '9' => 'auth.inflstatus9',
    ],


    'applycond' => [
        '' => 'auth.applycond',
        '0' => 'auth.applycond0',
        '4' => 'auth.applycond4',
        '1' => 'auth.applycond1',
        '5' => 'auth.applycond5',
        '2' => 'auth.applycond2',
        '8' => 'auth.applycond8',
        '9' => 'auth.applycond9',
    ],

    'country' => [
             '1' => 'Japan',
             '2' => 'Afghanistan',
             '3' => 'Åland Islands',
             '4' => 'Albania',
             '5' => 'Algeria',
             '6' => 'American Samoa',
             '7' => 'Andorra',
             '8' => 'Angola',
             '9' => 'Anguilla',
             '10' => 'Antarctica',
             '11' => 'Antigua and Barbuda',
             '12' => 'Argentina',
             '13' => 'Armenia',
             '14' => 'Aruba',
             '15' => 'Australia',
             '16' => 'Austria',
             '17' => 'Azerbaijan',
             '18' => 'Bahamas',
             '19' => 'Bahrain',
             '20' => 'Bangladesh',
             '21' => 'Barbados',
             '22' => 'Belarus',
             '23' => 'Belgium',
             '24' => 'Belize',
             '25' => 'Benin',
             '26' => 'Bermuda',
             '27' => 'Bhutan',
             '28' => 'Bolivia',
             '29' => 'Bosnia and Herzegovina',
             '30' => 'Botswana',
             '31' => 'Bouvet Island',
             '32' => 'Brazil',
             '33' => 'British Indian Ocean Territory',
             '34' => 'Brunei Darussalam',
             '35' => 'Bulgaria',
             '36' => 'Burkina Faso',
             '37' => 'Burundi',
             '38' => 'Cambodia',
             '39' => 'Cameroon',
             '40' => 'Canada',
             '41' => 'Cape Verde',
             '42' => 'Cayman Islands',
             '43' => 'Central African Republic',
             '44' => 'Chad',
             '45' => 'Chile',
             '46' => 'China',
             '47' => 'Christmas Island',
             '48' => 'Cocos (Keeling) Islands',
             '49' => 'Colombia',
             '50' => 'Comoros',
             '51' => 'Congo',
             '52' => 'Congo, The Democratic Republic of The',
             '53' => 'Cook Islands',
             '54' => 'Costa Rica',
             '55' => 'Cote Divoire',
             '56' => 'Croatia',
             '57' => 'Cuba',
             '58' => 'Cyprus',
             '59' => 'Czech Republic',
             '60' => 'Denmark',
             '61' => 'Djibouti',
             '62' => 'Dominica',
             '63' => 'Dominican Republic',
             '64' => 'Ecuador',
             '65' => 'Egypt',
             '66' => 'El Salvador',
             '67' => 'Equatorial Guinea',
             '68' => 'Eritrea',
             '69' => 'Estonia',
             '70' => 'Ethiopia',
             '71' => 'Falkland Islands (Malvinas)',
             '72' => 'Faroe Islands',
             '73' => 'Fiji',
             '74' => 'Finland',
             '75' => 'France',
             '76' => 'French Guiana',
             '77' => 'French Polynesia',
             '78' => 'French Southern Territories',
             '79' => 'Gabon',
             '80' => 'Gambia',
             '81' => 'Georgia',
             '82' => 'Germany',
             '83' => 'Ghana',
             '84' => 'Gibraltar',
             '85' => 'Greece',
             '86' => 'Greenland',
             '87' => 'Grenada',
             '88' => 'Guadeloupe',
             '89' => 'Guam',
             '90' => 'Guatemala',
             '91' => 'Guernsey',
             '92' => 'Guinea',
             '93' => 'Guineabissau',
             '94' => 'Guyana',
             '95' => 'Haiti',
             '96' => 'Heard Island and Mcdonald Islands',
             '97' => 'Holy See (Vatican City State)',
             '98' => 'Honduras',
             '99' => 'Hong Kong',
             '100' => 'Hungary',
             '101' => 'Iceland',
             '102' => 'India',
             '103' => 'Indonesia',
             '104' => 'Iran, Islamic Republic of',
             '105' => 'Iraq',
             '106' => 'Ireland',
             '107' => 'Isle of Man',
             '108' => 'Israel',
             '109' => 'Italy',
             '110' => 'Jamaica',
             '111' => 'Jersey',
             '112' => 'Jordan',
             '113' => 'Kazakhstan',
             '114' => 'Kenya',
             '115' => 'Kiribati',
             '116' => 'Korea Democratic Peoples Republic of',
             '117' => 'Korea Republic of',
             '118' => 'Kuwait',
             '119' => 'Kyrgyzstan',
             '120' => 'Lao Peoples Democratic Republic',
             '121' => 'Latvia',
             '122' => 'Lebanon',
             '123' => 'Lesotho',
             '124' => 'Liberia',
             '125' => 'Libyan Arab Jamahiriya',
             '126' => 'Liechtenstein',
             '127' => 'Lithuania',
             '128' => 'Luxembourg',
             '129' => 'Macao',
             '130' => 'Macedonia, The Former Yugoslav Republic of',
             '131' => 'Madagascar',
             '132' => 'Malawi',
             '133' => 'Malaysia',
             '134' => 'Maldives',
             '135' => 'Mali',
             '136' => 'Malta',
             '137' => 'Marshall Islands',
             '138' => 'Martinique',
             '139' => 'Mauritania',
             '140' => 'Mauritius',
             '141' => 'Mayotte',
             '142' => 'Mexico',
             '143' => 'Micronesia, Federated States of',
             '144' => 'Moldova, Republic of',
             '145' => 'Monaco',
             '146' => 'Mongolia',
             '147' => 'Montenegro',
             '148' => 'Montserrat',
             '149' => 'Morocco',
             '150' => 'Mozambique',
             '151' => 'Myanmar',
             '152' => 'Namibia',
             '153' => 'Nauru',
             '154' => 'Nepal',
             '155' => 'Netherlands',
             '156' => 'Netherlands Antilles',
             '157' => 'New Caledonia',
             '158' => 'New Zealand',
             '159' => 'Nicaragua',
             '160' => 'Niger',
             '161' => 'Nigeria',
             '162' => 'Niue',
             '163' => 'Norfolk Island',
             '164' => 'Northern Mariana Islands',
             '165' => 'Norway',
             '166' => 'Oman',
             '167' => 'Pakistan',
             '168' => 'Palau',
             '169' => 'Palestinian Territory, Occupied',
             '170' => 'Panama',
             '171' => 'Papua New Guinea',
             '172' => 'Paraguay',
             '173' => 'Peru',
             '174' => 'Philippines',
             '175' => 'Pitcairn',
             '176' => 'Poland',
             '177' => 'Portugal',
             '178' => 'Puerto Rico',
             '179' => 'Qatar',
             '180' => 'Reunion',
             '181' => 'Romania',
             '182' => 'Russian Federation',
             '183' => 'Rwanda',
             '184' => 'Saint Helena',
             '185' => 'Saint Kitts and Nevis',
             '186' => 'Saint Lucia',
             '187' => 'Saint Pierre and Miquelon',
             '188' => 'Saint Vincent and The Grenadines',
             '189' => 'Samoa',
             '190' => 'San Marino',
             '191' => 'Sao Tome and Principe',
             '192' => 'Saudi Arabia',
             '193' => 'Senegal',
             '194' => 'Serbia',
             '195' => 'Seychelles',
             '196' => 'Sierra Leone',
             '197' => 'Singapore',
             '198' => 'Slovakia',
             '199' => 'Slovenia',
             '200' => 'Solomon Islands',
             '201' => 'Somalia',
             '202' => 'South Africa',
             '203' => 'South Georgia and The South Sandwich Islands',
             '204' => 'Spain',
             '205' => 'Sri Lanka',
             '206' => 'Sudan',
             '207' => 'Suriname',
             '208' => 'Svalbard and Jan Mayen',
             '209' => 'Swaziland',
             '210' => 'Sweden',
             '211' => 'Switzerland',
             '212' => 'Syrian Arab Republic',
             '213' => 'Taiwan',
             '214' => 'Tajikistan',
             '215' => 'Tanzania, United Republic of',
             '216' => 'Thailand',
             '217' => 'Timor-leste',
             '218' => 'Togo',
             '219' => 'Tokelau',
             '220' => 'Tonga',
             '221' => 'Trinidad and Tobago',
             '222' => 'Tunisia',
             '223' => 'Turkey',
             '224' => 'Turkmenistan',
             '225' => 'Turks and Caicos Islands',
             '226' => 'Tuvalu',
             '227' => 'Uganda',
             '228' => 'Ukraine',
             '229' => 'United Arab Emirates',
             '230' => 'United Kingdom',
             '231' => 'United States',
             '232' => 'United States Minor Outlying Islands',
             '233' => 'Uruguay',
             '234' => 'Uzbekistan',
             '235' => 'Vanuatu',
             '236' => 'Venezuela',
             '237' => 'Viet Nam',
             '238' => 'Virgin Islands, British',
             '239' => 'Virgin Islands, U.S.',
             '240' => 'Wallis and Futuna',
             '241' => 'Western Sahara',
             '242' => 'Yemen',
             '243' => 'Zambia',
             '244' => 'Zimbabwe',
            ],

    'listed' => [
        '0' => 'auth.listed0',
        '1' => 'auth.listed1',
        '2' => 'auth.listed2',
    ],


    'occupation' => [
        '0' => 'auth.occupation0',
        '1' => 'auth.occupation1',
        '2' => 'auth.occupation2',
        '3' => 'auth.occupation3',
        '4' => 'auth.occupation4',
        '5' => 'auth.occupation5',
    ],


    'invoicetype' => [
        '0' => 'auth.invoicetype0',
        '1' => 'auth.invoicetype1',
        '2' => 'auth.invoicetype2',
    ],


    'closemonth' => [
        '0' => 'auth.closemonth0',
        '1' => 'auth.closemonth1',
        '2' => 'auth.closemonth2',
        '3' => 'auth.closemonth3',
        '4' => 'auth.closemonth4',
        '5' => 'auth.closemonth5',
        '6' => 'auth.closemonth6',
        '7' => 'auth.closemonth7',
        '8' => 'auth.closemonth8',
        '9' => 'auth.closemonth9',
        '10' => 'auth.closemonth10',
        '11' => 'auth.closemonth11',
        '12' => 'auth.closemonth12',
    ],






];
